# GAT model configuration
model:
  _target_: src.models.gat.GATEncoder
  in_channels: ${data.num_features}
  hidden_dim: 64
  out_channels: 64
  num_layers: 2
  dropout: 0.5
  activation: "elu"
  heads: 8
  concat: true
  negative_slope: 0.2
